### ISSUE TITLE
Things we want to learn about

### ISSUE THREAD

**Issue by rpherbig** [sep/electron-demo-app#2]
building
- [x] javascript
- [x] typescript?
- [x] linting

deploying
- [x] do we need to use `make`? - due to compilation, npm scripts may not be sufficient
- [x] windows
- [ ] mac
- [x] linux (different by distro?)
- [x] [cross-platform compilation](https://stackoverflow.com/questions/66963414/electronforge-build-app-for-other-platform) (local Windows, CI/CD linux, etc.) ([article on using GitHub action](https://github.com/marketplace/actions/electron-builder-action))
- [ ] [build all platforms at once](https://www.electron.build/)
    - It looks like we can build the windows installer from linux, but we need a mac to make the mac installer.
- [ ] "installing"
  - [X] Windows Installer 
  - [ ] Linux Installer
  - [ ] Mac Installer
- [ ] [auto updating](https://www.electronjs.org/docs/latest/api/auto-updater)

[automated testing](https://www.electronjs.org/docs/latest/tutorial/automated-testing)
- [x] unit - `jest`
- [x] unit - `react-test-renderer`
- ~~unit - `@testing-library/react`~~ - this library [only lets you examine the DOM](https://testing-library.com/docs/react-testing-library/intro/#this-solution) and we wanted the ability to test React components themselves
- ~~unit - `enzyme`~~ - [There is no adapter](https://github.com/enzymejs/enzyme/issues/2429) to allow Enzyme to work with the latest version of React (17.x). The PR has been [stalled for over a year](https://github.com/enzymejs/enzyme/pull/2430). There is [an unofficial adapter](https://github.com/wojtekmaj/enzyme-adapter-react-17) which we decided not to use.
- ~~integration - `Cypress`~~ - [Cypress has stopped supporting Electron](https://www.cypress.io/blog/2019/09/26/testing-electron-js-applications-using-cypress-alpha-release/)
- ~~integration - `Spectron`~~ - [Spectron has been deprecated](https://www.electronjs.org/blog/spectron-deprecation-notice)
- [x] integration - `Selenium` via [WebdriverJS](https://www.electronjs.org/docs/latest/tutorial/using-selenium-and-webdriver#setting-up-with-webdriverjs)
    - Note: requires rebuilding the app before running tests if changes were made to it or it has never been built
    - [x] requires a compiled Electron app and running Webdriver server to run locally
    - [x] headless locally
         - [x] headless windows - via [cross-env](https://github.com/kentcdodds/cross-env/issues/257)
         - [x] headless linux - via xvfb
         - [x] headless osx - via xvfb & homebrew
    - [x] headless on the CI/CD server requires [using xvfb](https://github.com/juliangruber/browser-run/issues/147), maybe we can use a [special GitHub Action](https://github.com/marketplace/actions/gabrielbb-xvfb-action)
- [x] integration - `Playwright` [integrated with Electron](https://playwright.dev/docs/api/class-electron) plus [Playwright Test](https://playwright.dev/docs/api/class-test) (see also ["Playwright vs Webdriver"](https://medium.com/slalom-build/playwright-vs-webdriver-the-future-of-browser-automation-854a7ae63218))
     - Note: requires browsers to support the [DevTools protocol.](https://wicg.github.io/devtools-protocol/) Not a problem for Electron, but could be if the UI is hosted as a web site and required to support older browsers (e.g. Internet Explorer). 
     - Note: requires rebuilding the app before running tests if changes were made to it or it has never been built
     - Note: for an Electron app, Playwright can be installed faster with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm i -D playwright`
     - [x] headless locally
         - [x] headless windows - via [cross-env](https://github.com/kentcdodds/cross-env/issues/257)
         - [x] headless linux - via xvfb
         - [x] headless osx - via xvfb & homebrew
    - [x] headless on the CI/CD server
- ~~system level/UI~~: there aren't any external dependencies to justify this level of testing.

cross-platform?
- [ ] if/when deploying to different platforms, how much is custom?
- [ ] background services
- [ ] native components
- [ ] System tray icon (Windows) and the equivalent for Mac and Linux
   - [x] Windows
   - [x] Linux
   - [ ] OSx
    - Need to capture the system tray object as a variable to avoid garbage collection and the tray going away
- [ ] [Mac-specific conventions](https://www.turtle-techies.com/how-to-package-your-multiplatform-electron-app/)

[what does interacting with local resources look like?](https://www.electronjs.org/docs/latest/tutorial/devices)
- [ ] USB/HID
- [ ] Bluetooth
- [ ] files/disk
- [ ] database
- [ ] what about elevated access?
- [ ] [use of IPC](https://github.com/reZach/secure-electron-template/blob/master/docs/newtoelectron.md)

logging
- [ ] splunk

ui framework
- [x] use `React `
- [x] use `Angular`
    - See https://www.logicflow.ai/blog/params/post/2543411/
    - From: https://angular.io/guide/setup-local
    - Note: don't search for "angular" - that will bring up results for angular.js that are a decade old. Use "angular.io" in searches.
    - Note: don't try to create components by hand, use `ng generate component`.
- ~~SPA/routing~~ - this is typically a concern of the UI framework and shouldn't be any different within Electron
- [x] open multiple windows and have them communicate with each other
    - Note: two windows can communicate, but have to use the main process as an intermediary. This is by (Electron's) design. See the chat app's "whisper" for an example.
- ~~[Vue, Ember, Backbone?](https://javascript.plainenglish.io/top-5-frontend-frameworks-to-learn-in-2022-57b76a6508dd)~~: we decided not to pursue this because the integration of these frameworks won't be significantly different than the React or Angular examples.

Localization/internationalization
- [ ] do it

**Comment by rpherbig** [comment]
Integration with React & Angular?

SPA/routing?

**Comment by rpherbig** [comment]
System tray icon (Windows) and the equivalent for Mac and Linux

**Comment by rpherbig** [comment]
TODO: Let's add some notes on what didn't work

TODO: Let's add some links for the sources we've been using

**Comment by rpherbig** [comment]
Playwright: `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm i -D playwright`

**Comment by rpherbig** [comment]
Selenium: will need to rebuild the app if changes were made to it or it has never been built

**Comment by rpherbig** [comment]
It looks like Cypress might support the Electron _browser_: https://docs.cypress.io/guides/guides/launching-browsers#Electron-Browser and https://docs.cypress.io/guides/guides/cross-browser-testing

I'm unclear if that is different than supporting an Electron _app_. We might want to revisit that.

**Comment by Skytherin** [comment]
FYI, if you ever need to debug electron-forge, you can use syntax like `DEBUG=electron-packager timeout 2m npx electron-forge make --platform win32`

**Comment by Skytherin** [comment]
FYI: electron-packager timed out when packaging ng w/ default settings. We fixed this by ignoring all @angular packages as follows:

```
"packagerConfig": {
        "ignore": [
          "node_modules/@angular"
        ]
      },
```

My preference would be to:
1 - webpack the main process so we can simply ignore everything in node_modules
2 - use a packager that allows us to whitelist what gets included in the package instead of a blacklist.

**Comment by Skytherin** [comment]
We tried using electron-builder because we thought it supported multi-platform builds from a single platform. It does not: linux builds on windows have been broken for at least 3 years and don't appear to be on anyone's radar to fix. Mac builds can only be built on mac.

It was a bit snappier to make builds (after the first one which caches some stuff) on windows; I don't know if we'd see the same performance improvement on Windows.
